# Generated by Django 5.0.3 on 2024-03-17 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'am_laboratories',
            },
        ),
        migrations.CreateModel(
            name='Meds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.BigIntegerField(unique=True)),
                ('fabric_price_no_taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_sale_price_government', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'am_meds',
            },
        ),
        migrations.CreateModel(
            name='Substances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'am_substances',
            },
        ),
        migrations.CreateModel(
            name='LaboratoriesMeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratories')),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.meds')),
            ],
            options={
                'db_table': 'am_laboratories_meds',
            },
        ),
        migrations.AddField(
            model_name='meds',
            name='substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.substances'),
        ),
    ]
